name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y liblua5.4-dev

      - name: Build
        run: zig build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pears-build
          path: zig-out/bin/pears
