name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        zig-version: [0.11.0]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ matrix.zig-version }}

    - name: Install Dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y liblua5.4-dev

    - name: Install Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install lua

    - name: Build
      run: zig build

    - name: Run Tests
      run: zig build test-all

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pears-${{ matrix.os }}
        path: zig-out/bin/pears
